// =========  GETTING ========= //
export const GET_MENU_ACTIVE = 'GET_MENU_ACTIVE';

export const GET_FILTER_ACTIVE = 'GET_FILTER_ACTIVE';
export const GET_OPTION_MANOS = 'GET_OPTION_MANOS';
export const GET_OPTION_UBICACION = 'GET_OPTION_UBICACION';
export const GET_OPTION_TEMAS = 'GET_OPTION_TEMAS';
export const GET_OPTION_USO = 'GET_OPTION_USO';

// =========  AUTHENTICAT ========= //
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FALL = 'FETCH_AUTH_FALL';
export const FETCH_AUTH_LOGOUT = 'FETCH_AUTH_LOGOUT';
